_format_version: "3.0"
_transform: true

services:
  - name: core-api
    url: http://ametis-core-api:8080
    routes:
      - name: core-api-v1
        paths:
          - /v1
          - /v3
          - /swagger-ui
          - /swagger-ui.html
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS

  - name: agent-factory-app
    url: http://ametis-agent-factory-app:8083
    routes:
      - name: agent-factory-api
        paths:
          - /api/agent-factory
        strip_path: false
        methods:
          - GET
          - POST
          - PATCH
          - DELETE
          - OPTIONS
