services:
  newsletter-web:
    build:
      context: ../../frontend/newsletter-app
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_NEWSLETTER_API_BASE_URL: ${NEWSLETTER_API_BASE_URL:-http://localhost:8082}
        NEXT_PUBLIC_NEWSLETTER_WEB_URL: ${NEWSLETTER_WEB_URL:-http://localhost:3100}
        NEXT_PUBLIC_API_BASE_URL: ${HUB_API_BASE_URL:-http://localhost:8000}
        NEXT_PUBLIC_KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL:-http://localhost:8081/realms/ametis/protocol/openid-connect/auth}
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${NEWSLETTER_KEYCLOAK_CLIENT_ID:-newsletter-web}
    image: ametis/newsletter-web:0.1.0
    container_name: ametis-newsletter-web
    environment:
      NEXT_PUBLIC_NEWSLETTER_API_BASE_URL: ${NEWSLETTER_API_BASE_URL:-http://localhost:8082}
      NEXT_PUBLIC_HUB_URL: ${HUB_WEB_URL:-http://localhost:3000}
      NEXT_PUBLIC_NEWSLETTER_WEB_URL: ${NEWSLETTER_WEB_URL:-http://localhost:3100}
      NEXT_PUBLIC_API_BASE_URL: ${HUB_API_BASE_URL:-http://localhost:8000}
      NEXT_PUBLIC_KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL:-http://localhost:8081/realms/ametis/protocol/openid-connect/auth}
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${NEWSLETTER_KEYCLOAK_CLIENT_ID:-newsletter-web}
    ports:
      - "3100:3100"
